### ISSUE TITLE
What are the system specs?

### ISSUE THREAD

**Issue by tejasvi** [akulagrawal/iitg_gpu#1]
Like RAM, storage (ephemeral or persistent), CPU, GPU model, etc.

**Comment by parthatom** [comment]
Maybe adding a FAQ section would be useful, for people who aren't aware of the presence of this resource.

**Comment by akulagrawal** [comment]
Yes, it would be great if you can generate a pull request with your questions in an FAQ section, I'll be adding the corresponding answers. Probably the fastest way I can think of.

**Comment by tejasvi** [comment]
@akulagrawal If you still have access, can you add the output for `sudo dmidecode`? If it is not available, use `sudo apt install dmidecode` on debian based distros. Nothing too urgent because I won't be heading back to campus until next year :)

**Comment by akulagrawal** [comment]
@tejasvi First of all, I don't think your question makes sense. Secondly, I feel it would probably be wrong to make any info about the GPU cluster public. Anyway, this repo doesn't aim for that. Closing this issue. @parthatom please open another issue in case you still have some doubt. Thanks!
